title: "Let me tell you some story's"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.483871
  brandStrength: 0.75
  lightness: 0.8476703
  brandColors:
    - '#415975'
    - '#6A84A5'
    - '#FFFFFF'
    - '#A3D0F7'
    - '#9E9E9E'
  rhythmicContrast: 0.5806451
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: wendymontellano
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2759857
layout_spectrum: 0.9229391
