name: wendymontellano
favicon: null
layout_spectrum: 0.9649914391338825
typography_spectrum: 0.23312
title: "Let me tell you some story's"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8161036721430719
  lightness: 0.47524138586595654
  saturation: 0.7113077510148287
  rhythmicContrast: 0.936653709737584
purpose: []
