name: wendymontellano
favicon: null
layout_spectrum: 0.9229391
typography_spectrum: 0.2759857
title: "Let me tell you some story's"
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#6AEAB9'
    - '#ED4956'
    - '#8A8A8A'
    - '#5D2B9E'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
