title: "Let me tell you some story's"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7437276
  brandStrength: 0.8100358
  rhythmicContrast: 0.7114695
  brandColors:
    - '#E3D9E0'
    - '#302F28'
    - '#CFB4A3'
    - '#4B774B'
    - '#88A377'
  lightness: 0.3476703
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: wendymontellano
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7741935
layout_spectrum: 0.2365591
