title: "Let me tell you some story's"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.483871
  brandStrength: 0.7759857
  lightness: 0.8476703
  brandColors:
    - '#FAD5DD'
    - '#FDF6A6'
    - '#664362'
    - '#C7ADB3'
    - '#7F7275'
  rhythmicContrast: 0.5806451
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: wendymontellano
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7741935
layout_spectrum: 0.2365591
